version: "3.5"

services:
  app-main:
    build: .
    image: bksynapse/apis:$VERSION
    environment:
      - BKSYN_DATA_ROOT=/data
      - BKSYN_NODEDB_HOST=10.198.54.231
      - BKSYN_NODEDB_PORT=17017
    volumes:
      - type: bind
        target: /app/logs
        source: ./logs
      - type: bind
        target: /app/configs
        source: ./configs
      - type: bind
        target: /data
        source: /home/common/bksynapse
    network_mode: host
  
