version: "3.5"

services:
  app-main:
    build: .
    image: bksynapse/apis:$VERSION-dev
    volumes:
      - type: bind
        target: /app
        source: ./
    environment:
      - APP_CONF=configs/app.dev.py
    command: python3 app.py
    restart: on-failure
