version: "3.5"

services:
  app-main:
    build: .
    image: bksynapse/system:$VERSION
    environment:
      - BKSYN_DATA_ROOT=/data
      - APP_JWT_KEY=dsfkjoj3nr034n1  # Change these in prod
    volumes:
      - type: bind
        target: /app/logs
        source: ./logs
      - type: bind
        target: /app/configs
        source: ./configs
      - type: bind
        target: /data
        source: /mnt/bksynapse
    network_mode: host
  
