version: "3.5"

services:
  app-main:
    build: .
    image: bksynapse/apis:$VERSION
    environment:
      - BKSYN_DATA_ROOT=/data
      - BKSYN_BTL_TCP_INCLUDE=10.42.0.0/24
      - HOROVOD_START_TIMEOUT=6000
    volumes:
      - type: bind
        target: /app/logs
        source: ./logs
      - type: bind
        target: /app/configs
        source: ./configs
      - type: bind
        target: /data
        source: /mnt/shared/bksynapse
    network_mode: host
  
