version: "3.5"

services:
  app:
    build: .
    image: bkdigits/web:$APP_VERSION
    ports:
      - "$HTTPS_PORT:443"
      - "$HTTP_PORT:80"
    volumes:
      - type: bind
        target: /var/log/nginx
        source: ./logs
