version: "3.5"

services:
  node:
    build: .
    image: bksynapse/node:$VERSION
    volumes:
      - type: bind
        source: /mnt/bksynapse
        target: /data
      - type: bind
        source: ./logs
        target: /app/logs
    environment:
      - BKSYN_DATA_ROOT=/data
      - BKSYN_NODE_ADDRESS=192.168.1.6
      - BKSYN_NODE_TYPE=cpu
    network_mode: host
    command: bash -c "/usr/sbin/sshd -p 17992; python worker.py --id Desktop"
