version: "3.5"

services:
  node:
    build: .
    image: bksynapse/node:$VERSION
    volumes:
      - type: bind
        source: /home/common/bksynapse
        target: /data
    environment:
      - BKSYN_NODEDB_HOST=localhost
      - BKSYN_NODEDB_PORT=17017
      - BKSYN_DATA_DIR=/data
      - BKSYN_NODE_ADDRESS=10.198.54.231
      - BKSYN_NODE_TYPE=cpu
    network_mode: host
