version: "3.5"

services:
  app-main:
    build: .
    image: bkdigits/node:$APP_VERSION
    volumes:
      - type: bind
        target: /app/logs
        source: ./logs
      - type: bind
        target: /app/configs
        source: ./configs
    ports:
      - "17957:22"
