version: "3.5"

volumes:
  app-nodes-db-data:

services:
  app-main:
    build: .
    image: bkdigits/system:$APP_VERSION
    environment:
      - BK_DIGITS_DATA_ROOT=/app/data
      - APP_JWT_KEY=dsfkjoj3nr034n1  # Change these in prod
    volumes:
      - type: bind
        target: /app/logs
        source: ./logs
      - type: bind
        target: /app/configs
        source: ./configs
      - type: bind
        target: /app/data
        source: ./data
    ports:
      - 17000:5000
    depends_on:
      - app-nodes-db
  app-node:
    image: bkdigits/system:$APP_VERSION
    volumes:
      - type: bind
        target: /app/logs
        source: ./logs
      - type: bind
        target: /app/configs
        source: ./configs
  app-nodes-db:
    image: mongo:latest
    ports:
      - 17001:27017
    volumes:
      - type: volume
        target: /data/db
        source: app-nodes-db-data
